version: "3.9"

services:
  auth-service:
    image: dendriel/npc-data-manager-auth:latest
    restart: always
    ports:
      - 8080:8080
    working_dir: /app
    environment:
      - MYSQL_DB=the_quest
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=docker
      - MYSQL_PASS=pass
  storage-service:
    image: dendriel/npc-data-manager-storage:latest
    restart: always
    ports:
      - 8082:8082
    working_dir: /app
    volumes:
      - c:\.aws:/root/.aws:ro
    environment:
      - MYSQL_DB=the_quest
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=docker
      - MYSQL_PASS=pass
      - AUTH_URL=http://auth-service:8080
  rest-service:
    image: dendriel/config-creator-rest
    restart: always
    ports:
      - 8081:8081
    environment:
      - MONGO_DB_HOST=host.docker.internal
      - MONGO_DB_NAME=config_creator
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=root
      - MONGO_DB_PASS=pass
      - AUTH_SERVICE_URL=http://auth-service:8080
      - EXPORTER_QUEUE_URL=http://sqs-service:9324
      - AWS_ACCESS_KEY_ID=1111
      - AWS_SECRET_KEY=2222
      - SERVICE_URL=http://host.docker.internal:3000
      - SERVICE_AUTH_KEY=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZXJ2aWNlLnVzZXIwMSIsImV4cCI6MTYzNDA2OTQwMywiaWF0IjoxNjMxNDc3NDAzfQ.ZT3R7PSqQ2SmQ4vkyCxZb2BB7oObgl6cyGk0LtUBJZQ
    depends_on:
      sqs-service:
        condition: service_healthy
  exporter-service:
    image: dendriel/config-creator-exporter
    restart: always
    environment:
      - SERVICE_URL=http://host.docker.internal:3000
      - QUEUE_URL=http://sqs-service:9324/queue/export-request
      - AUTH_KEY=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZXJ2aWNlLnVzZXIwMSIsImV4cCI6MTYzNDA2OTQwMywiaWF0IjoxNjMxNDc3NDAzfQ.ZT3R7PSqQ2SmQ4vkyCxZb2BB7oObgl6cyGk0LtUBJZQ
    depends_on:
      sqs-service:
        condition: service_healthy
  sqs-service:
    image: roribio16/alpine-sqs:latest
    restart: always
    ports:
      - 9325:9325 # web interface
      - 9324:9324 # consumer
    volumes:
      - ./conf/sqs:/opt/custom
    healthcheck:
      test: "/usr/bin/wget http://localhost:9325"
      timeout: 5s
      retries: 40
